CREATE TABLE IF NOT EXISTS article
(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(150) NOT NULL,
  content TEXT NOT NULL,
  publishedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME
)
