CREATE TABLE IF NOT EXISTS comment
(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  content TEXT NOT NULL,
  nick VARCHAR(20) NOT NULL,
  article_id INT NOT NULL,
  FOREIGN KEY (article_id) REFERENCES article(id),
  publishedAt DATETIME DEFAULT CURRENT_TIMESTAMP
)
